language: node_js
node_js:
  - lts/dubnium
services:
  - docker
jobs:
  include:
  - name: Default Ganache
    script: npm run test-norpc
  - name: Geth
    script: npm run test-geth
  - name: OpenEthereum
    script:
      - PASSFILE=$(mktemp)
      - echo '' > $PASSFILE
      - CONTAINER_ID=$(docker run --rm -d -p 8545:8545 -p 8546:8546 -v $PASSFILE:/tmp/pass openethereum/openethereum --config dev --jsonrpc-interface=all --ws-interface=all --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password /tmp/pass)
      - npx wait-port -t 10000 localhost:8545
      - npx truffle test --network local
    after_script:
      - docker logs $CONTAINER_ID
      - docker stop $CONTAINER_ID
